# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jstdutil}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christian Johansen"]
  s.date = %q{2009-11-04}
  s.description = %q{Thin wrapper over Google's JsTestDriver that adds colors and autotest}
  s.email = %q{christian@cjohansen.no}
  s.executables = ["jstestdriver", "jsautotest"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/jsautotest",
     "bin/jstestdriver",
     "lib/jstdutil.rb",
     "lib/jstdutil/autotest.rb",
     "lib/jstdutil/cli.rb",
     "lib/jstdutil/hooks.rb",
     "lib/jstdutil/jstestdriver/config.rb",
     "lib/jstdutil/jstestdriver/server.rb",
     "lib/jstdutil/redgreen.rb",
     "lib/jstdutil/test_file.rb",
     "lib/jstdutil/test_runner.rb",
     "lib/watchr_script",
     "test/cli_test.rb",
     "test/jstdutil_test.rb",
     "test/jstestdriver_config_test.rb",
     "test/jstestdriver_test.rb",
     "test/redgreen_test.rb",
     "test/test_file_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/cjohansen/jstdutil}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{jstdutil}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Thin wrapper over Google's JsTestDriver that adds colors and autotest}
  s.test_files = [
    "test/cli_test.rb",
     "test/jstdutil_test.rb",
     "test/jstestdriver_config_test.rb",
     "test/jstestdriver_test.rb",
     "test/redgreen_test.rb",
     "test/test_file_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<watchr>, [">= 0"])
      s.add_runtime_dependency(%q<rake>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<watchr>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<watchr>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
  end
end

